"use client";
import React, { useState } from 'react';

const Form = () => {
  const [vuelo, setVuelo] = useState<string>("");
  const [tipoVuelo, setTipoVuelo] = useState<string>('na');
  const [salida, setSalida] = useState<string>("");
  const [llegada, setLlegada] = useState<string>("");
  const [horaSalida, setHoraSalida] = useState<string>("");
  const [horaLlegada, setHoraLlegada] = useState<string>("");
  const [origen, setOrigen] = useState<string>("Bogota");
  const [destino, setDestino] = useState<string>("Bogota");
  const [aeronave, setAeronave] = useState<string>("");
  const [pasajeros, setPasajeros] = useState<number | ''>('');
  const [tiquete, setTiquete] = useState<number | ''>('');
  const [impuestos, setImpuestos] = useState<number | ''>('');
  const [sobretasa, setSobretasa] = useState<number | ''>('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const numericPasajeros = Number(pasajeros);
    const numericTiquete = Number(tiquete);
    const numericImpuestos = Number(impuestos);
    const numericSobretasa = Number(sobretasa);

    if (
      numericPasajeros <= 0 ||
      numericTiquete <= 0 ||
      numericImpuestos < 0 ||
      numericSobretasa < 0
    ) {
      setError('Valores numéricos deben ser positivos y válidos');
      return;
    }

    setError(null);
    setLoading(true);
    setSuccessMessage(null); // Reset success message

    const formData = {
      id: 0, // Assuming ID is generated by the server
      flightNumber: vuelo,
      basePrice: numericTiquete,
      taxPercentage: numericImpuestos,
      surcharge: numericSobretasa,
      scales: [
        {
          airplaneModel: {
            id: aeronave
          },
          originAirport: {
            id: origen
          },
          destinationAirport: {
            id: destino
          },
          departureDate: `${salida} ${horaSalida}:00`,
          arrivalDate: `${llegada} ${horaLlegada}:00`
        }
      ],
      flightType: tipoVuelo
    };

    console.log("Sending data:", JSON.stringify(formData, null, 2)); // To check the data being sent

    try {
      const response = await fetch('http://localhost:8019/modulo-19/v1/flights/add', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      });

      console.log('Response:', response);

      if (!response.ok) {
        const errorMessage = await response.text();
        throw new Error(`Network response was not ok: ${errorMessage}`);
      }

      const responseData = await response.json();
      console.log('Flight data saved successfully:', responseData);
      setSuccessMessage('El vuelo se ha creado exitosamente.');
    } catch (error: any) {  // Asegúrate de que el error tenga un tipo `any`
      console.error('There was a problem with the fetch operation:', error);
      setError(`Hubo un problema al crear el vuelo: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleOptionChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTipoVuelo(e.target.value);
  };

  const handleNumberChange = (setter: React.Dispatch<React.SetStateAction<number | ''>>) => (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setter(value === '' ? '' : Number(value));
  };

  return (
    <div className='px-32 w-[1255px] mt-8'>
      {error && <h2 className="bg-red-800 text-white text-center p-3 uppercase font-bold mb-3 rounded-md">{error}</h2>}
      {successMessage && <h2 className="bg-green-800 text-white text-center p-3 uppercase font-bold mb-3 rounded-md">{successMessage}</h2>}

      <form onSubmit={handleSubmit}>
        <div className='pt-5 relative'>
          <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Número de vuelo</label>
          <input type='text' name='vuelo' className='border-2 border-gray-300 pl-5 h-14 w-[1000px]' placeholder='SA-1234' value={vuelo} onChange={(e) => setVuelo(e.target.value)} />
        </div>

        <div className='pt-5'>
          <label className='block'>Tipo de vuelo: </label>
          <div className='pt-2'>
            <label className='pr-12'>
              <input type='radio' name='tipo' value='Nacional' className='mr-2' checked={tipoVuelo === 'Nacional'} onChange={handleOptionChange} />
              Nacional
            </label>
            <label>
              <input type='radio' name='tipo' value='Internacional' className='mr-2' checked={tipoVuelo === 'Internacional'} onChange={handleOptionChange} />
              Internacional
            </label>
          </div>
        </div>

        <div className='pt-5 relative'>
          <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Ciudad de origen: </label>
          <select name='origen' className='border-2 border-gray-300 pl-5 h-14 w-[1000px]' value={origen} onChange={(e) => setOrigen(e.target.value)}>
            <option value="Bogota">(BOG) Aeropuerto Internacional El Dorado - Bogotá</option>
            <option value="Cali">(CLO) Aeropuerto Internacional Alfonso Bonilla Aragón - Cali</option>
            <option value="Cartagena">(CTG) Aeropuerto Internacional Rafael Núñez - Cartagena</option>
            <option value="Medellin">(MDE) Aeropuerto Internacional José María Córdova - Rionegro/Medellín</option>
            <option value="Paris">(CDG) Aeropuerto Charles de Gaulle - París, Francia</option>
            <option value="Dubai">(DXB) Aeropuerto Internacional de Dubái - Dubái, Emiratos Árabes Unidos</option>
            <option value="Nueva York">(JFK) Aeropuerto Internacional John F. Kennedy - Nueva York, Estados Unidos</option>
            <option value="Ciudad de Mexico">(MEX) Aeropuerto Internacional Benito Juárez - Ciudad de México, México</option>
          </select>
        </div>

        <div className='pt-5 relative'>
          <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-36 h-1 align-top'>Ciudad de destino: </label>
          <select name='destino' className='border-2 border-gray-300 pl-5 h-14 w-[1000px]' value={destino} onChange={(e) => setDestino(e.target.value)}>
            <option value="Bogota">(BOG) Aeropuerto Internacional El Dorado - Bogotá</option>
            <option value="Cali">(CLO) Aeropuerto Internacional Alfonso Bonilla Aragón - Cali</option>
            <option value="Cartagena">(CTG) Aeropuerto Internacional Rafael Núñez - Cartagena</option>
            <option value="Medellin">(MDE) Aeropuerto Internacional José María Córdova - Rionegro/Medellín</option>
            <option value="Paris">(CDG) Aeropuerto Charles de Gaulle - París, Francia</option>
            <option value="Dubai">(DXB) Aeropuerto Internacional de Dubái - Dubái, Emiratos Árabes Unidos</option>
            <option value="Nueva York">(JFK) Aeropuerto Internacional John F. Kennedy - Nueva York, Estados Unidos</option>
            <option value="Ciudad de Mexico">(MEX) Aeropuerto Internacional Benito Juárez - Ciudad de México, México</option>
          </select>
        </div>

        <div className='flex'>
          <div className='pt-5 pr-12 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Fecha de salida: </label>
            <input type='date' className='border-2 border-gray-300 pl-5 h-14 w-[474px]' name='fechaSalida' value={salida} onChange={(e) => setSalida(e.target.value)} />
          </div>

          <div className='pt-5 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-28 h-1 align-top'>Hora de salida: </label>
            <input type='time' className='border-2 border-gray-300 pl-5 h-14 w-[476px]' value={horaSalida} name='horaSalida' onChange={(e) => setHoraSalida(e.target.value)} />
          </div>
        </div>

        <div className='flex'>
          <div className='pt-5 pr-12 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-36 h-1 align-top'>Fecha de llegada: </label>
            <input type='date' className='border-2 border-gray-300 pl-5 h-14 w-[474px]' value={llegada} name='fechaLlegada' onChange={(e) => setLlegada(e.target.value)} />
          </div>

          <div className='pt-5 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Hora de llegada: </label>
            <input type='time' className='border-2 border-gray-300 pl-5 h-14 w-[476px]' value={horaLlegada} name='horaLlegada' onChange={(e) => setHoraLlegada(e.target.value)} />
          </div>
        </div>

        <div className='flex'>
          <div className='pt-5 pr-12 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Tipo de aeronave: </label>
            <input type='text' className='border-2 border-gray-300 pl-5 h-14 w-[600px]' value={aeronave} name='tipoAeronave' onChange={(e) => setAeronave(e.target.value)} />
          </div>

          <div className='pt-5 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-52 h-1 align-top'>Cantidad máxima de pasajeros: </label>
            <input type='number' className='border-2 border-gray-300 pl-5 h-14 w-[350px]' value={pasajeros} name='cantidadPasajeros' onChange={handleNumberChange(setPasajeros)} />
          </div>
        </div>

        <div className='flex'>
          <div className='pt-5 pr-8 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-32 h-1 align-top'>Precio de tiquete: </label>
            <input type='number' className='border-2 border-gray-300 pl-5 h-14 w-[435px]' value={tiquete} name='precioTicket' onChange={handleNumberChange(setTiquete)} />
          </div>

          <div className='pt-5 pr-8 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-24 h-1 align-top'>Impuestos(%): </label>
            <input type='number' className='border-2 border-gray-300 pl-5 h-14 w-[250px]' value={impuestos} name='impuestos' onChange={handleNumberChange(setImpuestos)} />
          </div>

          <div className='pt-5 relative'>
            <label className='absolute top-0 left-0 ml-7 py-3 px-3 text-xs font-light bg-slate-50 w-24 h-1 align-top'>Sobretasa(%): </label>
            <input type='number' className='border-2 border-gray-300 pl-5 h-14 w-[250px]' value={sobretasa} name='sobretasa' onChange={handleNumberChange(setSobretasa)} />
          </div>
        </div>

        <button className='bg-blue-400 text-white mt-4 rounded-sm px-6 h-10' type='submit'>CREAR VUELO</button>
      </form>

      {loading && <p>Cargando...</p>}
    </div>
  );
}

export default Form;
